"""
Generated automatically.  Do not modify!
"""

_globals = {
    'CHARM_SHA_CELL_AQ': 0,
    'CHARM_CRD_CELL_GRID': -2,
    'CHARM_CRD_CELL_SCATTERED': -1,
    'CHARM_CRD_POINT_SCATTERED': 1,
    'CHARM_CRD_POINT_GRID': 2,
    'CHARM_CRD_POINT_GRID_GL': 3,
    'CHARM_CRD_POINT_GRID_DH1': 4,
    'CHARM_CRD_POINT_GRID_DH2': 5,
    'CHARM_ERR_MAX_FILE': 4096,
    'CHARM_ERR_MAX_FUNC': 256,
    'CHARM_ERR_MAX_MSG': 4096,
    'CHARM_ERR_MAX_LEVEL': 10,
    'CHARM_ERR_MALLOC_FAILURE': 'Memory allocation failure.',
    'CHARM_FAILURE': -1,
    'CHARM_SUCCESS': 0,
    'CHARM_EMEM': 1,
    'CHARM_EFUNCARG': 2,
    'CHARM_EFILEIO': 3,
    'CHARM_EFFTWINIT': 4,
    'CHARM_SHC_WRITE_TBL_N': 0,
    'CHARM_SHC_WRITE_TBL_M': 1,
    'CHARM_VERSION_MAJOR': 0,
    'CHARM_VERSION_MINOR': 2,
    'CHARM_VERSION_PATCH': 0,
    'CHARM_VERSION_STRING': '0.2.0-dev',
    'CHARM_LEG_PNMJ_ORDER_MNJ': 0,
    'CHARM_LEG_PNMJ_ORDER_MJN': 1,
}

